pipe:
  name: 'godot-python-pipe'
  bufferSize: 8192
engine:
  timeScale: 1.0
  ticksPerSecond: 60
tests:
  runTests: true
  runTestsWhenOpenedViaCommandLine: false
  runSlowTests: true
  passUncertainTestsWhenFailed: true
  printAdditionalLogs: true
environment:
  energyBaseLossPerSecond: 2.0
  energyLossPerSecondPer100UnitsOfMovement: 0.2
  energyLossPerSecondTurn: 0.2
  energyUsedReproduction: 50
  healthLossPerSecond: 5.0
  healthRegenPerSecond: 1.0
  score:
    foodEaten: 100
    energyMax: 100
    healthMax: 100
    reproduction: 200
    waterPenalty: 50
  bucketSize: 256
  agentSightProcessEveryNthFrame: 3
  agentWaterPenaltyUpdateEveryNthFrame: 6
  supervisorAgentSpawnSafeDistance: 16
  supervisorAgentMaxSpawnTryCount: 50
  seed: 0
display:
  resolution:
    x: 1920
    y: 1080
  isFullscreen: true
  isMouseLocked: true
controls:
  zoomSensitivity: 1
  maxZoom: 3
  minZoom: 0.3
  edgeMoveEnabled: true
  edgeMoveMargin: 50
  edgeMoveSpeed: 3
save:
  savePath: user://
