pipe:
  name: 'godot-python-pipe'
  bufferSize: 64
engine:
  timeScale: 3.0 # multiplier
  ticksPerSecond: 60
tests:
  runTests: true
  runTestsWhenOpenedViaCommandLine: false
  runSlowTests: true
  passUncertainTestsWhenFailed: true
  printAdditionalLogs: true
environment:
  energyLossPerSecond: 3.0
  healthLossPerSecond: 5.0
  healthRegenPerSecond: 1.0
