name: build


on:
  pull_request:
#    paths:
#      - 'core/**'


env:
  PYTHON_VERSION: '3.11'


jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup python
      id: python-setup
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Check if cache exists
      uses: actions/cache/restore@v3
      id: cache-check
      with:
        lookup-only: true
        path: ./.venv/
        key: ${{ runner.os }}-${{ steps.python-setup.outputs.python-version }}-venv-${{ hashFiles('core/requirements.txt') }}

    - name: Install dependencies if no cache found
      if: steps.cache-check.outputs.cache-hit != 'true'
      run: |
        python -m venv ./.venv
        source ./.venv/bin/activate
        python -m pip install -r core/requirements.txt

    - name: List installed packages
      if: steps.cache-check.outputs.cache-hit != 'true'
      run: |
        source ./.venv/bin/activate
        pip list

    - name: Upload new cache if exists
      if: steps.cache-check.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: ./.venv/
        key: ${{ runner.os }}-${{ steps.python-setup.outputs.python-version }}-venv-${{ hashFiles('core/requirements.txt') }}
