name: dotnet format


on:
  push:
    paths:
      - "engine/**.cs"
      - "engine/.editorconfig"


env:
  DOTNET_VERSION: '7.0.x'


jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format
        run: dotnet format './engine/AI-controlled-models-analysis.sln' --verify-no-changes --verbosity diagnostic