name: linters

on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Check cache directory before caching
      run: ls -la ~/.cache/pip
    - name: Cache pip dependencies
      id: ruff-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('core/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Check cache hit
      run: echo "Cache hit: ${{ steps.ruff-cache.outputs.cache-hit }}"
    - name: Install requirements
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r core/requirements.txt
    - name: Check cache directory after installation
      run: ls -la ~/.cache/pip
    - name: ruff
      run: ruff check core --verbose --output-format=github

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Check cache directory before caching
      run: ls -la ~/.cache/pip
    - name: Cache pip dependencies
      id: mypy-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('core/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Check cache hit
      run: echo "Cache hit: ${{ steps.mypy-cache.outputs.cache-hit }}"
    - name: Install requirements
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r core/requirements.txt
    - name: Check cache directory after installation
      run: ls -la ~/.cache/pip
    - name: mypy
      run: mypy core --show-error-codes --pretty --show-column-numbers --show-error-context
