name: linters

on: push

env:
  PYTHON_VERSION: '3.11'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Create cache directory
      run: mkdir -p ~/.cache/pip
    - name: Cache pip dependencies
      id: ruff-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python${{ env.PYTHON_VERSION }}/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('core/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install requirements
      if: steps.ruff-cache.outputs.cache-hit != 'true'
      run: pip install -r core/requirements.txt
    - name: Check installed packages
      run: pip list
    - name: ruff
      run: ruff check core --verbose --output-format=github

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Create cache directory
      run: mkdir -p ~/.cache/pip
    - name: Cache pip dependencies
      id: mypy-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python${{ env.PYTHON_VERSION }}/site-packages
        key: ${{ runner.os }}-pip-${{ hashFiles('core/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install requirements
      if: steps.mypy-cache.outputs.cache-hit != 'true'
      run: pip install -r core/requirements.txt
    - name: Check installed packages
      run: pip list
    - name: mypy
      run: mypy core --show-error-codes --pretty --show-column-numbers --show-error-context
