name: linters

on:
  push

env:
  MYPY_REPORT_DIR: mypy_report

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: 'core/requirements.txt'
    - run: pip install -r core/requirements.txt
    - name: ruff
      run: ruff check core --verbose --output-format=github

  mypy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: 'core/requirements.txt'
      - run: pip install -r core/requirements.txt
      - name: mypy
        run: mypy core --show-error-codes --pretty --show-column-numbers --show-error-context --cobertura-xml-report $MYPY_REPORT_DIR
      - name: Type Hint Coverage Summary Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: mypy_report/*.xml
          minimum_coverage: 75
          show_missing: true
          link_missing_lines: true
          run: pycobertura show --format github-annotation mypy_report/*.xml