name: python_tests.yaml
on:
  workflow_run:
    workflows:
      - python_linters
    types:
      - completed

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Python setup
        id: python-setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Load cached virtual environment
        uses: actions/cache/restore@v3
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.python-setup.outputs.python-version }}-venv-${{ hashFiles('core/requirements.txt') }}

      - name: Test with pytest
        run: |
          source ./.venv/bin/activate  
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m