name: Python linters

on:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: 'core/requirements.txt'

      - name: Install dependencies
        run: pip install -r core/requirements.txt

      - name: Run Ruff
        run: ruff check core --verbose --output-format=github

  mypy:
    runs-on: ubuntu-latest
    env:
      MYPY_REPORT_DIR: mypy_report
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      checks: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: 'core/requirements.txt'

      - name: Install dependencies
        run: pip install -r core/requirements.txt

      - name: Run Mypy
        run: mypy core --show-error-codes --pretty --show-column-numbers --show-error-context --cobertura-xml-report $MYPY_REPORT_DIR

      - name: Type Hint Coverage Summary Report
        uses: 5monkeys/cobertura-action@master
        run: echo "$MYPY_REPORT_DIR/*.xml"; echo "$MYPY_REPORT_DIR /*.xml"
        with:
          path: mypy_report/*.xml
          minimum_coverage: 80
          show_missing: true
          link_missing_lines: true
          report_name: Type hint coverage
